blog_list:
    path: /blog
    controller: App\Controller\BlogController::list

blog_show:
    path: /blog/posts/{id}
    controller: App\Controller\BlogController::show

blog_category_show:
    path: /blog/categories/{id}
    controller: App\Controller\BlogController::show_category

blog_month_show:
    path: /blog/month
    controller: App\Controller\BlogController::show_month